spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: chayotte
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/chayotte-realm

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: master
    username: admin
    password: admin
    client-id: admin-cli
    target-realm: chayotte-realm

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    enabled: true
    path: swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  forward-headers-strategy: framework

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] %5p %logger{36}: %msg | Line: %line%n"
  level:
    root: INFO
    br.com.chayotte: INFO
    org.springframework: INFO
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
