version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8180:8180
    command: start-dev --http-port=8180